spring:
  application:
    name: 03-crudhibernate
  datasource:
    url: jdbc:mysql://localhost:3306/hb-04-one-to-many-uni
    username: springstudent
    password: springstudent

logging:
  level:
    org:
      hibernate:
        SQL: trace
        orm:
          jdbc:
            bind: trace

